# Generated by Django 3.2.4 on 2021-11-13 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20211113_2136'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Imager',
        ),
    ]
